### PR TITLE
Merge Request!

### PR DESCRIPTION
**Pull request by thebaolin**
Hey Patrick!

Hope you're doing well. 

I forked your repo and made a minor addition (added a comment to main.cpp).

Let me know what you think and if it works. 

Best,
Baolin Chang

### CODE REVIEW

**Comment by patging** [comment]
Hi Paulina! 

Sorry about what I did to your repo last week :( . 

I ran your copy on my windows PC. I don't have my unix machine, can you run it on yours and lmk if it works? 

Tysm

Best regards
Patrick Ging

**Comment by thebaolin** [comment]
Hey Patrick!

It's all good, I'll have my partner fix it, and it was a nice addition to my repo haha.

It works on my PC! Thanks for checking.

Do you have any other questions?

Best,
Baolin Chang

**Comment by patging** [comment]
Alr. It looks good to me. Merging!

Thanks sm for your help Paulina! Enjoy your holiday.

Best regards
Patrick Ging :)

**Comment by thebaolin** [comment]
Yay! 

Have fun in Ireland, and make sure to bring back some souvenirs :)

Best,
Baolin Chang

**Pull request merged**
